apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: postgresql
    repo: https://charts.bitnami.com/bitnami
    version: "12.5.8"
    releaseName: my-postgres-database
    namespace: default
    valuesFile: my-values.yaml
    valuesInline:
      auth:
        username: my-user
        password: my-password
