{{- if and (.Values.blackbox.enabled) (.Values.blackbox.blackboxProber.enabled) (.Values.blackbox.blackboxProber.networkPolicy.enabled) (or (.Values.blackbox.helmTargets.service) (and (.Values.ingress.enabled) (.Values.blackbox.helmTargets.ingress))) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "automating-blackbox-monitoring-for-your-helm-chart.fullname" . }}-for-blackbox-prober
spec:
  ingress:
    - ports:
        - port: {{ .Values.blackbox.blackboxProber.port }}
          protocol: TCP
      {{- if .Values.blackbox.blackboxProber.namespace }}
      from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.blackbox.blackboxProber.namespace | quote }}
      {{- end }}
  podSelector:
    matchLabels:
      {{- include "automating-blackbox-monitoring-for-your-helm-chart.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
{{- end }}
