---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mychart
spec:
  project: default
  source:
    repoURL: https://github.com/christianknell/blog-code
    targetRevision: main
    path: deploying-helm-charts-through-argocd/2
    helm:
      releaseName: mychart
      valueFiles:
        - values.yaml
        - values-production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
