apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helmfile-example
spec:
  project: default
  source:
    repoURL: https://github.com/christianknell/blog-code.git
    targetRevision: main
    path: deploying-helm-charts-using-argocd-and-helmfile
  destination:
    server: https://kubernetes.default.svc
    namespace: default
