repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: postgresql
    namespace: default
    chart: bitnami/postgresql
    values:
      - auth:
          rootPassword: "J7Fa_T4~@.HQg1w8BP2d#9Lm*G[D3I+5"
